version: '3.9'
services:
 nginx:
  image: nginx:latest
  ports:
   - 81:80
  volumes:
   - volume_qualquer:/usr/share/nginx/html
  networks:
   - appnet
  depends_on:
   httpd:
    condition: service_healthy

 httpd:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - 80:80
  command: sh -c "sleep 10 && httpd-foreground"
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost"]
   interval: 15s
   timeout: 10s
   retries: 3

  volumes:
   - ./www:/usr/local/apache2/htdocs
  networks:
   - appnet

networks:
 appnet:
  name: appnetwork

volumes:
 volume_qualquer:
